component_depth: 1
languages:
- java
exclude:
- ./bin/.*
- ./bin/data/.*
- ./bin/data/abinit/.*
- ./bin/data/aces2/.*
- ./bin/data/adf/.*
- ./bin/data/arff/.*
- ./bin/data/asn/.*
- ./bin/data/asn/pubchem/.*
- ./bin/data/chebi/.*
- ./bin/data/cml/.*
- ./bin/data/crystclust/.*
- ./bin/data/ctx/.*
- ./bin/data/gamess/.*
- ./bin/data/gaussian/.*
- ./bin/data/ghemical/.*
- ./bin/data/hin/.*
- ./bin/data/ichi/.*
- ./bin/data/inchi/.*
- ./bin/data/jaguar/.*
- ./bin/data/mdl/.*
- ./bin/data/mol2/.*
- ./bin/data/pcore/.*
- ./bin/data/pdb/.*
- ./bin/data/pmp/.*
- ./bin/data/shelx/.*
- ./bin/data/smiles/.*
- ./bin/data/vasp/.*
- ./bin/data/xyz/.*
- ./bin/net/.*
- ./bin/net/sf/.*
- ./bin/net/sf/cdk/.*
- ./bin/net/sf/cdk/tools/.*
- ./bin/net/sf/cdk/tools/bibtex/.*
- ./bin/net/sf/cdk/tools/checkdoctest/.*
- ./bin/net/sf/cdk/tools/copyright/.*
- ./bin/net/sf/cdk/tools/coverage/.*
- ./bin/net/sf/cdk/tools/doclets/.*
- ./bin/org/.*
- ./bin/org/openscience/.*
- ./bin/org/openscience/cdk/.*
- ./bin/org/openscience/cdk/annotations/.*
- ./bin/org/openscience/cdk/aromaticity/.*
- ./bin/org/openscience/cdk/atomtype/.*
- ./bin/org/openscience/cdk/atomtype/mapper/.*
- ./bin/org/openscience/cdk/charges/.*
- ./bin/org/openscience/cdk/config/.*
- ./bin/org/openscience/cdk/config/atomtypes/.*
- ./bin/org/openscience/cdk/config/data/.*
- ./bin/org/openscience/cdk/config/fragments/.*
- ./bin/org/openscience/cdk/config/isotopes/.*
- ./bin/org/openscience/cdk/controller/.*
- ./bin/org/openscience/cdk/coverage/.*
- ./bin/org/openscience/cdk/debug/.*
- ./bin/org/openscience/cdk/dict/.*
- ./bin/org/openscience/cdk/dict/data/.*
- ./bin/org/openscience/cdk/dict/data/react/.*
- ./bin/org/openscience/cdk/event/.*
- ./bin/org/openscience/cdk/exception/.*
- ./bin/org/openscience/cdk/fingerprint/.*
- ./bin/org/openscience/cdk/fingerprint/data/.*
- ./bin/org/openscience/cdk/formula/.*
- ./bin/org/openscience/cdk/formula/rules/.*
- ./bin/org/openscience/cdk/geometry/.*
- ./bin/org/openscience/cdk/geometry/alignment/.*
- ./bin/org/openscience/cdk/geometry/surface/.*
- ./bin/org/openscience/cdk/graph/.*
- ./bin/org/openscience/cdk/graph/invariant/.*
- ./bin/org/openscience/cdk/graph/invariant/exception/.*
- ./bin/org/openscience/cdk/graph/matrix/.*
- ./bin/org/openscience/cdk/graph/rebond/.*
- ./bin/org/openscience/cdk/gui/.*
- ./bin/org/openscience/cdk/gui/smiles/.*
- ./bin/org/openscience/cdk/inchi/.*
- ./bin/org/openscience/cdk/index/.*
- ./bin/org/openscience/cdk/interfaces/.*
- ./bin/org/openscience/cdk/io/.*
- ./bin/org/openscience/cdk/io/cml/.*
- ./bin/org/openscience/cdk/io/cml/data/.*
- ./bin/org/openscience/cdk/io/formats/.*
- ./bin/org/openscience/cdk/io/inchi/.*
- ./bin/org/openscience/cdk/io/iterator/.*
- ./bin/org/openscience/cdk/io/iterator/event/.*
- ./bin/org/openscience/cdk/io/listener/.*
- ./bin/org/openscience/cdk/io/program/.*
- ./bin/org/openscience/cdk/io/pubchemxml/.*
- ./bin/org/openscience/cdk/io/random/.*
- ./bin/org/openscience/cdk/io/setting/.*
- ./bin/org/openscience/cdk/isomorphism/.*
- ./bin/org/openscience/cdk/isomorphism/matchers/.*
- ./bin/org/openscience/cdk/isomorphism/matchers/smarts/.*
- ./bin/org/openscience/cdk/isomorphism/mcss/.*
- ./bin/org/openscience/cdk/iupac/.*
- ./bin/org/openscience/cdk/iupac/parser/.*
- ./bin/org/openscience/cdk/layout/.*
- ./bin/org/openscience/cdk/layout/templates/.*
- ./bin/org/openscience/cdk/libio/.*
- ./bin/org/openscience/cdk/libio/cml/.*
- ./bin/org/openscience/cdk/libio/md/.*
- ./bin/org/openscience/cdk/limitations/.*
- ./bin/org/openscience/cdk/limitations/tools/.*
- ./bin/org/openscience/cdk/math/.*
- ./bin/org/openscience/cdk/math/qm/.*
- ./bin/org/openscience/cdk/modeling/.*
- ./bin/org/openscience/cdk/modeling/builder3d/.*
- ./bin/org/openscience/cdk/modeling/builder3d/data/.*
- ./bin/org/openscience/cdk/modeling/forcefield/.*
- ./bin/org/openscience/cdk/modeling/forcefield/data/.*
- ./bin/org/openscience/cdk/modulesuites/.*
- ./bin/org/openscience/cdk/nonotify/.*
- ./bin/org/openscience/cdk/pharmacophore/.*
- ./bin/org/openscience/cdk/protein/.*
- ./bin/org/openscience/cdk/protein/data/.*
- ./bin/org/openscience/cdk/qsar/.*
- ./bin/org/openscience/cdk/qsar/descriptors/.*
- ./bin/org/openscience/cdk/qsar/descriptors/atomic/.*
- ./bin/org/openscience/cdk/qsar/descriptors/atomic/data/.*
- ./bin/org/openscience/cdk/qsar/descriptors/atompair/.*
- ./bin/org/openscience/cdk/qsar/descriptors/bond/.*
- ./bin/org/openscience/cdk/qsar/descriptors/data/.*
- ./bin/org/openscience/cdk/qsar/descriptors/molecular/.*
- ./bin/org/openscience/cdk/qsar/descriptors/protein/.*
- ./bin/org/openscience/cdk/qsar/model/.*
- ./bin/org/openscience/cdk/qsar/model/R/.*
- ./bin/org/openscience/cdk/qsar/model/R2/.*
- ./bin/org/openscience/cdk/qsar/model/data/.*
- ./bin/org/openscience/cdk/qsar/result/.*
- ./bin/org/openscience/cdk/reaction/.*
- ./bin/org/openscience/cdk/reaction/mechanism/.*
- ./bin/org/openscience/cdk/reaction/type/.*
- ./bin/org/openscience/cdk/reaction/type/parameters/.*
- ./bin/org/openscience/cdk/renderer/.*
- ./bin/org/openscience/cdk/renderer/color/.*
- ./bin/org/openscience/cdk/ringsearch/.*
- ./bin/org/openscience/cdk/ringsearch/cyclebasis/.*
- ./bin/org/openscience/cdk/similarity/.*
- ./bin/org/openscience/cdk/smiles/.*
- ./bin/org/openscience/cdk/smiles/data/.*
- ./bin/org/openscience/cdk/smiles/smarts/.*
- ./bin/org/openscience/cdk/smiles/smarts/parser/.*
- ./bin/org/openscience/cdk/smiles/smarts/parser/visitor/.*
- ./bin/org/openscience/cdk/structgen/.*
- ./bin/org/openscience/cdk/structgen/stochastic/.*
- ./bin/org/openscience/cdk/structgen/stochastic/operator/.*
- ./bin/org/openscience/cdk/templates/.*
- ./bin/org/openscience/cdk/templates/data/.*
- ./bin/org/openscience/cdk/templates/saturatedhydrocarbons/.*
- ./bin/org/openscience/cdk/tools/.*
- ./bin/org/openscience/cdk/tools/diff/.*
- ./bin/org/openscience/cdk/tools/diff/tree/.*
- ./bin/org/openscience/cdk/tools/features/.*
- ./bin/org/openscience/cdk/tools/manipulator/.*
- ./bin/org/openscience/cdk/tools/periodictable/.*
- ./bin/org/openscience/cdk/validate/.*
- ./bin/org/openscience/jchempaint/.*
- ./bin/org/openscience/jchempaint/action/.*
- ./bin/org/openscience/jchempaint/applet/.*
- ./bin/org/openscience/jchempaint/application/.*
- ./bin/org/openscience/jchempaint/controller/.*
- ./bin/org/openscience/jchempaint/controller/undoredo/.*
- ./bin/org/openscience/jchempaint/dialog/.*
- ./bin/org/openscience/jchempaint/dialog/editor/.*
- ./bin/org/openscience/jchempaint/dialog/templates/.*
- ./bin/org/openscience/jchempaint/dialog/templates/Alkaloids/.*
- ./bin/org/openscience/jchempaint/dialog/templates/Beta_Lactams/.*
- ./bin/org/openscience/jchempaint/dialog/templates/Carbohydrates/.*
- ./bin/org/openscience/jchempaint/dialog/templates/Inositols/.*
- ./bin/org/openscience/jchempaint/dialog/templates/Lipids/.*
- ./bin/org/openscience/jchempaint/dialog/templates/Miscellaneous/.*
- ./bin/org/openscience/jchempaint/dialog/templates/Nucleosides/.*
- ./bin/org/openscience/jchempaint/dialog/templates/Porphyrins/.*
- ./bin/org/openscience/jchempaint/dialog/templates/Steroids/.*
- ./bin/org/openscience/jchempaint/io/.*
- ./bin/org/openscience/jchempaint/matchers/.*
- ./bin/org/openscience/jchempaint/renderer/.*
- ./bin/org/openscience/jchempaint/renderer/color/.*
- ./bin/org/openscience/jchempaint/renderer/elements/.*
- ./bin/org/openscience/jchempaint/renderer/elements/path/.*
- ./bin/org/openscience/jchempaint/renderer/font/.*
- ./bin/org/openscience/jchempaint/renderer/generators/.*
- ./bin/org/openscience/jchempaint/renderer/generators/parameter/.*
- ./bin/org/openscience/jchempaint/renderer/selection/.*
- ./bin/org/openscience/jchempaint/renderer/visitor/.*
- ./bin/org/openscience/jchempaint/undoredo/.*
- ./cdk/.*
- ./cdk/META-INF/.*
- ./cdk/deterministic/.*
- ./cdk/develjar/.*
- ./cdk/doc/.*
- ./cdk/doc/dict/.*
- ./cdk/doc/dict/xsl/.*
- ./cdk/doc/javadoc/.*
- ./cdk/doc/refs/.*
- ./cdk/jar/.*
- ./cdk/perf/.*
- ./cdk/pmd/.*
- ./cdk/pmd/net/.*
- ./cdk/tools/.*
- ./lib/.*
- ./org.openscience.cdk.jchempaint30/.*
- ./org.openscience.cdk.jchempaint30/META-INF/.*
- ./org.openscience.cdk.jchempaint30/applettests/.*
- ./org.openscience.cdk.jchempaint30/lib/.*
- ./org.openscience.cdk.jchempaint30/po/.*
- ./org.openscience.cdk.jchempaint30/po/classes/.*
- ./org.openscience.cdk.jchempaint30/po/classes/app/.*
- ./org.openscience.cdk.jchempaint30/po/classes/app/i18n/.*
